"""add all_filings to subscriptions

Revision ID: 14890def496a
Revises: 9fbf53e1c090
Create Date: 2026-06-09 15:35:37.724302

"""
from alembic import op
import sqlalchemy as sa


revision = '14890def496a'
down_revision = '9fbf53e1c090'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'subscriptions',
        sa.Column('all_filings', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'all_filings')
    # ### end Alembic commands ###
