"""initial schema

Revision ID: 9fbf53e1c090
Revises: 
Create Date: 2026-06-09 14:29:26.014000

"""
from alembic import op
import sqlalchemy as sa


revision = '9fbf53e1c090'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('committees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('encrypted_id', sa.String(length=200), nullable=True),
    sa.Column('committee_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_committees_encrypted_id'), 'committees', ['encrypted_id'], unique=False)
    op.create_table('feed_items',
    sa.Column('guid_seq', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('committee_name', sa.String(length=500), nullable=False),
    sa.Column('report_type', sa.String(length=200), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('guid_url', sa.Text(), nullable=False),
    sa.Column('pub_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('guid_seq')
    )
    op.create_table('poller_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_poll_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_guid_seq', sa.Integer(), nullable=False),
    sa.Column('consecutive_errors', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('races',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('office_district_patterns', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscribers_email'), 'subscribers', ['email'], unique=True)
    op.create_table('filings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_item_seq', sa.Integer(), nullable=False),
    sa.Column('committee_id', sa.Integer(), nullable=True),
    sa.Column('report_type', sa.String(length=200), nullable=False),
    sa.Column('report_class', sa.String(length=20), nullable=False),
    sa.Column('is_amendment', sa.Boolean(), nullable=False),
    sa.Column('amends_filing_id', sa.Integer(), nullable=True),
    sa.Column('filed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['amends_filing_id'], ['filings.id'], ),
    sa.ForeignKeyConstraint(['committee_id'], ['committees.id'], ),
    sa.ForeignKeyConstraint(['feed_item_seq'], ['feed_items.guid_seq'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filings_committee_id'), 'filings', ['committee_id'], unique=False)
    op.create_index(op.f('ix_filings_feed_item_seq'), 'filings', ['feed_item_seq'], unique=True)
    op.create_index(op.f('ix_filings_report_class'), 'filings', ['report_class'], unique=False)
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.Text(), nullable=False),
    sa.Column('auth', sa.Text(), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.create_index(op.f('ix_push_subscriptions_subscriber_id'), 'push_subscriptions', ['subscriber_id'], unique=False)
    op.create_table('race_committees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('committee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['committee_id'], ['committees.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'committee_id')
    )
    op.create_index(op.f('ix_race_committees_committee_id'), 'race_committees', ['committee_id'], unique=False)
    op.create_index(op.f('ix_race_committees_race_id'), 'race_committees', ['race_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('committee_id', sa.Integer(), nullable=True),
    sa.Column('wants_email', sa.Boolean(), nullable=False),
    sa.Column('wants_push', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['committee_id'], ['committees.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscriber_id', 'race_id', 'committee_id', name='uq_sub_target')
    )
    op.create_index(op.f('ix_subscriptions_committee_id'), 'subscriptions', ['committee_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_race_id'), 'subscriptions', ['race_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_subscriber_id'), 'subscriptions', ['subscriber_id'], unique=False)
    op.create_table('filing_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('line_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('supporting_opposing', sa.String(length=50), nullable=True),
    sa.Column('candidate_name', sa.String(length=500), nullable=True),
    sa.Column('office_district', sa.String(length=500), nullable=True),
    sa.Column('vendor_name', sa.String(length=500), nullable=True),
    sa.Column('vendor_address', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filing_lines_filing_id'), 'filing_lines', ['filing_id'], unique=False)
    op.create_index(op.f('ix_filing_lines_office_district'), 'filing_lines', ['office_district'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscriber_id', 'filing_id', 'channel', name='uq_notif_once')
    )
    op.create_index(op.f('ix_notifications_filing_id'), 'notifications', ['filing_id'], unique=False)
    op.create_index(op.f('ix_notifications_subscriber_id'), 'notifications', ['subscriber_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_subscriber_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_filing_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_filing_lines_office_district'), table_name='filing_lines')
    op.drop_index(op.f('ix_filing_lines_filing_id'), table_name='filing_lines')
    op.drop_table('filing_lines')
    op.drop_index(op.f('ix_subscriptions_subscriber_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_race_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_committee_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_race_committees_race_id'), table_name='race_committees')
    op.drop_index(op.f('ix_race_committees_committee_id'), table_name='race_committees')
    op.drop_table('race_committees')
    op.drop_index(op.f('ix_push_subscriptions_subscriber_id'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_index(op.f('ix_filings_report_class'), table_name='filings')
    op.drop_index(op.f('ix_filings_feed_item_seq'), table_name='filings')
    op.drop_index(op.f('ix_filings_committee_id'), table_name='filings')
    op.drop_table('filings')
    op.drop_index(op.f('ix_subscribers_email'), table_name='subscribers')
    op.drop_table('subscribers')
    op.drop_table('races')
    op.drop_table('poller_state')
    op.drop_table('feed_items')
    op.drop_index(op.f('ix_committees_encrypted_id'), table_name='committees')
    op.drop_table('committees')
    # ### end Alembic commands ###
